### ISSUE TITLE
Trying to use react hook within cellRenderer is not allowed.

### ISSUE THREAD

**Issue by genomics-geek** [Autodesk/react-base-table#77] opened 2019-08-21 13:45 UTC
I was trying to use a react-apollo-hook in a custom cellRenderer in order to load data into a modal if the user clicks.  However, I get the error message: `Invalid hook call: Hooks can only be called inside of the body of a function component.`

I believe it is because of the way cellRenderer is being called [here](https://github.com/Autodesk/react-base-table/blob/master/src/TableRow.js#L42-L50).

Is there a different way to accomplish this. Or is using hooks in a cell outside of the scope of this project?  Thanks for the help in advance.

For example I was trying to do something like this:

```javascript
import React from 'react'
import PropTypes from 'prop-types'
import { useLazyQuery } from '@apollo/react-hooks'
import { get } from 'lodash'

import { QUERY } from './queries'

export const InterpretationsCell = ({ cellData,  }) => {

  const [loadDetails, { loading, data }] = useLazyQuery(QUERY)

  ...do something
  
  return <p>{cellData}</p>
}

InterpretationsCell.propTypes = {
  column: PropTypes.shape({
    variantType: PropTypes.string.isRequired,
    idKey: PropTypes.string.isRequired,
  }).isRequired,
}

export default InterpretationsCell
```

**Comment by nihgwu** [comment] 2019-08-21 16:20
Hey, thanks for the report, I think it's caused by `renderElement` https://github.com/Autodesk/react-base-table/blob/master/src/utils.js#L3-L15, we call the function component as a function directly to avoid extra wrapper for the cell component in the component tree in react dev tools, so hooks is not supported right now, but definitely it should be fixed

**Comment by genomics-geek** [comment] 2019-08-21 16:46
@nihgwu that would be great, thanks!

**Closed** 2019-08-26 08:32 UTC
Labels: bug

**Comment by nihgwu** [comment] 2019-08-26 08:35
@genomics-geek fixed in v1.7.2

**Comment by nihgwu** [comment] 2019-08-27 03:43
@genomics-geek  I'd say that would be problematic if you use local state in cell renderer, as the component will be unmount when it's out of viewport by scrolling, and all the local state will be lost, from your snippet, I think you can use `onRowsRendered` to perform lazy data loading, and that's what we did internally, by that way you can load and cache on demand

**Comment by genomics-geek** [comment] 2019-08-29 14:43
@nihgwu - thanks for  the heads up.  Don't plan on using local state in the cellRenderer.
